const sql = require('mssql');
const { Pool } = require('pg');
let pool;
let pgPool;
const categories = new Set(['Mechanical','Electrical','Utility (Electricity)','Utility(Gas)','Process','Power','CCM']);
const number = v => { const n = Number(v); return Number.isFinite(n) ? n : 0; };
const date = v => v ? new Date(v).toISOString().slice(0, 10) : null;
async function db() {
  if (!pool) pool = await sql.connect({ server:process.env.MSSQL_SERVER, port:Number(process.env.MSSQL_PORT || 1433), user:process.env.MSSQL_USER, password:process.env.MSSQL_PASSWORD, database:process.env.MSSQL_DATABASE || 'DWH', options:{ encrypt:false, trustServerCertificate:true }, requestTimeout:60000 });
  return pool;
}
async function postgresFallback(from, to) {
  if (!pgPool) pgPool = new Pool({ host:process.env.PGHOST, user:process.env.PGUSER, port:Number(process.env.PGPORT || 5432), database:process.env.PGDATABASE, password:process.env.PGPASSWORD, ssl:{rejectUnauthorized:false} });
  const [oee, rca] = await Promise.all([
    pgPool.query("SELECT to_char(production_date,'YYYY-MM-DD') AS date,plant,machine,item,shift,shift_target_qty AS target,actual_output_qty AS actual,good_output_qty AS good,npt_loss_min,shift_duration_min,available_min FROM dwh_oee WHERE production_date BETWEEN $1::date AND $2::date ORDER BY production_date DESC", [from, to]),
    pgPool.query("SELECT log_date AS date,sbu,name,problem,status,priority FROM problem_solving_log WHERE log_date BETWEEN $1::date AND $2::date ORDER BY log_date DESC LIMIT 200", [from, to]),
  ]);
  let actual=0,good=0,target=0,available=0,shift=0,npt=0,events=0; const machines=new Map();
  oee.rows.forEach(x=>{actual+=number(x.actual);good+=number(x.good);target+=number(x.target);available+=number(x.available_min);shift+=number(x.shift_duration_min);npt+=number(x.npt_loss_min);if(number(x.npt_loss_min)>0){events++;const m=machines.get(x.machine)||{machine:x.machine,plant:x.plant,events:0,downtime:0};m.events++;m.downtime+=number(x.npt_loss_min);machines.set(x.machine,m);}});
  const byMachine=[...machines.values()].map(x=>({...x,mttr_min:x.events?x.downtime/x.events:0})).sort((a,b)=>b.downtime-a.downtime);
  return {from,to,yield:{records:oee.rows.length,total_target:target,total_actual:actual,total_good:good,yield_pct:actual?good/actual*100:null,by_plant:[],rows:oee.rows.slice(0,200).map(x=>({...x,yield_pct:number(x.actual)?number(x.good)/number(x.actual)*100:null}))},reliability:{breakdown_events:events,total_downtime_min:npt,available_min:available,mtbf_hours:events?Math.max(0,available-npt)/events/60:null,mttr_hours:events?npt/events/60:null,by_category:[],by_machine:byMachine,rows:[]},scheduled_maintenance:{total_min:0,planned_downtime_min:0,records:0,rows:[]},rca:rca.rows};
}
async function getReliability(from, to) {
  const p = await db();
  const y = await p.request().input('from', sql.NVarChar, from).input('to', sql.NVarChar, to).query(`SELECT dteProductionDate,strPlantName,strMachineName,stritemName,strShiftName,numShiftTargetQuantity,numActualOutputQuantity,numGoodOutputQuantity,numWastageTargetQuantity,numPlannedDowntimeMin,numAvailableMinute FROM mes.tblOeeProdWasteHeaderArc WHERE isActive=1 AND dteProductionDate>=@from AND dteProductionDate<=@to ORDER BY dteProductionDate DESC`);
  const npt = await p.request().input('from', sql.NVarChar, from).input('to', sql.NVarChar, to).query(`SELECT h.dteLossTimeDate,h.strPlantName,h.strWrokCenterName AS machine,r.strCategoryName,r.strReason,r.strBreakdownName,r.strReasonName,r.intLossTimeInMinutes FROM mes.tblNPTHeaderArc h JOIN mes.tblNPTRowArc r ON r.intNPTId=h.intNPTId WHERE h.isActive=1 AND r.isActive=1 AND h.dteLossTimeDate>=@from AND h.dteLossTimeDate<=@to ORDER BY h.dteLossTimeDate DESC`);
  const rc = await p.request().input('from', sql.NVarChar, from).input('to', sql.NVarChar, to).query(`SELECT TOP 200 intRCAAPId,strPotentialCause,strWhyOne,strWhyTwo,strWhyThree,strWhyFour,strWhyFive,strPossibleCountermeasures,strWhatActionIs,strActionStatus,dteScheduleTiming,dteCompletionDate,dteServerDateTime FROM mes.tblRCAAPArc WHERE isActive=1 AND dteServerDateTime>=@from AND dteServerDateTime<=@to ORDER BY dteServerDateTime DESC`);
  let actual=0, good=0, target=0, planned=0, available=0; const plants=new Map();
  const yieldRows=y.recordset.map(r=>{const a=number(r.numActualOutputQuantity),g=number(r.numGoodOutputQuantity); actual+=a;good+=g;target+=number(r.numShiftTargetQuantity);planned+=number(r.numPlannedDowntimeMin);available+=number(r.numAvailableMinute);const x=plants.get(r.strPlantName)||{actual:0,good:0};x.actual+=a;x.good+=g;plants.set(r.strPlantName,x);return {date:date(r.dteProductionDate),plant:r.strPlantName,machine:r.strMachineName,item:r.stritemName,shift:r.strShiftName,target:number(r.numShiftTargetQuantity),actual:a,good:g,waste:number(r.numWastageTargetQuantity),yield_pct:a?g/a*100:null};});
  let events=0,downtime=0,scheduled=0;const byCategory=new Map(),byMachine=new Map(),maintenance=[];const breakdown=[];
  npt.recordset.forEach(r=>{const mins=number(r.intLossTimeInMinutes),cat=(r.strCategoryName||'').trim();if(cat==='Schedule Maintenance'){scheduled+=mins;maintenance.push({date:date(r.dteLossTimeDate),plant:r.strPlantName,machine:r.machine,reason:r.strReason,loss_min:mins});return;}if(!categories.has(cat))return;events++;downtime+=mins;const c=byCategory.get(cat)||{events:0,downtime_min:0};c.events++;c.downtime_min+=mins;byCategory.set(cat,c);const m=byMachine.get(r.machine)||{machine:r.machine,plant:r.strPlantName,events:0,downtime:0};m.events++;m.downtime+=mins;byMachine.set(r.machine,m);if(breakdown.length<200)breakdown.push({date:date(r.dteLossTimeDate),plant:r.strPlantName,machine:r.machine,category:cat,breakdown:r.strBreakdownName,reason:r.strReasonName||r.strReason,loss_min:mins});});
  const mttr=events?downtime/events/60:null, mtbf=events?Math.max(0,available-downtime)/events/60:null;
  return {from,to,yield:{records:yieldRows.length,total_target:target,total_actual:actual,total_good:good,yield_pct:actual?good/actual*100:null,by_plant:[...plants].map(([plant,v])=>({plant,...v,yield_pct:v.actual?v.good/v.actual*100:null})),rows:yieldRows.slice(0,200)},reliability:{breakdown_events:events,total_downtime_min:downtime,available_min:available,mtbf_hours:mtbf,mttr_hours:mttr,by_category:[...byCategory].map(([category,v])=>({category,...v,avg_min:v.events?v.downtime_min/v.events:0})).sort((a,b)=>b.downtime_min-a.downtime_min),by_machine:[...byMachine.values()].map(v=>({...v,mttr_min:v.events?v.downtime/v.events:0})).sort((a,b)=>b.downtime-a.downtime).slice(0,30),rows:breakdown},scheduled_maintenance:{total_min:scheduled,planned_downtime_min:planned,records:maintenance.length,rows:maintenance.slice(0,100)},rca:rc.recordset.map(r=>({id:r.intRCAAPId,potential_cause:r.strPotentialCause,why1:r.strWhyOne,why2:r.strWhyTwo,why3:r.strWhyThree,why4:r.strWhyFour,why5:r.strWhyFive,countermeasures:r.strPossibleCountermeasures,action:r.strWhatActionIs,status:r.strActionStatus,schedule:date(r.dteScheduleTiming),completion:date(r.dteCompletionDate),logged:date(r.dteServerDateTime)}))};
}
module.exports = async (req,res) => { res.setHeader('Access-Control-Allow-Origin','*'); const today=new Date().toISOString().slice(0,10); try{return res.status(200).json(await getReliability(req.query.from||today,req.query.to||today));}catch(error){try{return res.status(200).json(await postgresFallback(req.query.from||today,req.query.to||today));}catch(fallbackError){return res.status(500).json({error:fallbackError.message});}} };
module.exports.getReliability=getReliability;
